name: Publish
on:
  push:
    branches:
      - master
jobs:
  testing:
    name: Testing
    runs-on: ubuntu-latest
    env:
      BS_ACCESS_KEY: ${{ secrets.BS_ACCESS_KEY }}
      BS_USERNAME: ${{ secrets.BS_USERNAME }}
      NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          always-auth: true
          node-version: '12.x'
      - name: Installing Dependencies and Building the Package
        run: yarn install --frozen-lockfile
      - name: Logging Target Dist Tag
        run: echo $(node ci/getNpmDistTag.js)
      - name: Publishing
        run: npm publish --tag $(node ci/getNpmDistTag.js)
